services:
  caddy:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ${PWD}/conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    environment:
      AWS_REGION: ${AWS_REGION}
      SITE_S3_BUCKET: ${SITE_S3_BUCKET}
      AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_OUTPUT: json

volumes:
  caddy_data:
  caddy_config:

